name: flutter_device_searcher
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://gogovan.hk
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.1.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: hk.gogovan.flutter_device_searcher
        pluginClass: FlutterDeviceSearcherPlugin
      ios:
        pluginClass: FlutterDeviceSearcherPlugin
