name: flutter_device_searcher_usb
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  flutter_device_searcher: 
    git:
      url: https://github.com/gogovan/flutter-device-searcher.git
      path: base
      ref: feat/EPT-3926

  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: hk.gogovan.flutter_device_searcher
        pluginClass: FlutterDeviceSearcherPlugin
